### ISSUE TITLE
A support thread that you might want to look at to expand the diacritics addon...

### ISSUE THREAD

**Issue by mnhende2** [hssm/anki-addons#12]
Dear hssm,

mnhende2 here.  Greetings.  Here is a support discussion thread on tenderapp that relates to your diacritics addon.  I thought you might be able to use it to expand the market for the addon.  If it isn't helpful, just ignore it.

http://anki.tenderapp.com/discussions/ankidesktop/9480-normal-search-cant-find-words-that-have-extra-accents-intended-to-learn-the-correct-pronunciation

Best!

**Comment by hssm** [comment]
Closing in favor of https://github.com/hssm/anki-addons/issues/15.
