### ISSUE TITLE
Ignore Accents Addon Breaks "Filter" button placement for LTR Language Interfaces in Anki 2.1

### ISSUE THREAD

**Issue by mnhende2** [hssm/anki-addons#18]
Greetings Hssm,

I hope you are well.  I just discovered today that that ignore accents addon is breaking the "filter" button location for LRT language interfaces in Anki 2.1.  (At least it does on my computers).  You can find the thread about it here.  https://anki.tenderapp.com/discussions/beta-testing/1230-rtl-suggestion

Best,
mnhende2

**Comment by hssm** [comment]
Thanks for letting me know. The order was broken regardless of RTL. I would never have noticed if you didn't point it out.

There's a new version on AnkiWeb with a fix.

**Comment by mnhende2** [comment]
Thanks Houssam.  Works great!  Appreciate the quick fix!
