### ISSUE TITLE
How to reset the saved information of this addon?

### ISSUE THREAD

**Issue by cjdduarte** [hssm/anki-addons#19]
How to reset the saved information of this addon?
All my fields are vertical and I can not use this addon anymore.

**Comment by hssm** [comment]
You can press `Ctrl+Shift+:` to open the debug console and put this in:
```
list_keys = list(mw.pm.profile.keys())
for k in list_keys:
  if k.startswith('multi_column_count'):
    mw.pm.profile.pop(k)
```

Then press `Ctrl+Enter` to run it.

**Comment by hssm** [comment]
Then either the add-on is not loading or it is conflicting with another one.

**Comment by cjdduarte** [comment]
Let me expose my problem.

![bug](https://user-images.githubusercontent.com/42243532/43929447-6851c1fc-9c0b-11e8-8f52-1365b786263c.jpg)

I do not know what happened. 
All my fields started to appear vertically in edit mode

**Comment by hssm** [comment]
If you disable the add-on, does it go back to normal?

If so, send me a copy of your collection so I can have a look.

**Comment by cjdduarte** [comment]
Yes. But I like this addon and would like to continue using it. I do not know how I changed the fields from horizontal to vertical. It was some shortcut.

My idea was to reset the variables. Or if you know which shortcut causes the fields to return to normal?

**Comment by cjdduarte** [comment]
I use multiple accounts.
The change was in only one and the error propagated to any deck that exists on any account. If you disable the addon, it gets normal

**Comment by hssm** [comment]
Without a reproducible test case I can't help.

My best guess is a conflict with another add-on. You can try disabling them one by one and see if the problem still happens.

**Comment by cjdduarte** [comment]
I will do this test and return

**Comment by Arthur-Milchior** [comment]
Hi

Since this add-on as not been updated since some months, I uploaded an updated version myself: https://ankiweb.net/shared/info/1159566613
You can use add-on's configuration to configure a lot of thing in it. In particular, you can edit the number of columns for each note type. Hope it'll help

**Comment by cjdduarte** [comment]
thank you. I will evaluate
