### ISSUE TITLE
Ignore cedilla and consider it a c

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [hssm/anki-addons#23]
Hi,
I was browsing my french cards and noticed that the search query "ça" does not include misspelings like "ca" which are frequent. Is it possible to include this into the addon ?
Thanks for your time :)

here's the wiki page : https://en.wikipedia.org/wiki/Cedilla

**Comment by hssm** [comment]
This is essentially the same thing as #22. I don't think there is anything I can readily do to support this since I'm just relying on built-in functionality which I can't change myself.
