### ISSUE TITLE
Question: why does anki find lower-case ü, but not upper-case Ü?

### ISSUE THREAD

**Issue by galantra** [hssm/anki-addons#25]
Why does anki find lower-case ü, but not upper-case Ü?
Without the addon, that is.

**Comment by hssm** [comment]
It find neither if you search `u`.

**Comment by galantra** [comment]
I should have made this clearer: I use a German keyboard that has a designated key for ü. Even though I search for ü, not u, vanilla anki will not show all results. Namely those where Ü is upper-case.
