### ISSUE TITLE
Images spilling over (not fitting to column width) since upgrading to 2.1

### ISSUE THREAD

**Issue by dolch8** [hssm/anki-addons#26]
The image shows what I mean. While using 2.0, images were reduced in size so they fit nicely into the column, but now they just spill over. I can't figure out what line of code is missing that will tell the images to respect the columns. Any advice is welcome. 

I'm using Anki 2.1.15 on MacOS Mojave 10.14.6

![Anki multi column issue](https://user-images.githubusercontent.com/58676769/70407026-579a1e00-1a08-11ea-82c8-c770eb964e76.png)

**Comment by dolch8** [comment]
I was able to fix the issue by editing __init__.py 

I added this line of code: 
`    s += '.mceTable img { max-width: 100%%; }';`

just below this line:
`    s += '.mceTable td .field { height: 100%%; }';`

**Comment by hssm** [comment]
Thanks. I'll add this into the next release.
